### ISSUE TITLE
Microsoft Edge Privacy Whitepaper

### ISSUE THREAD

**Issue by it-is-final** [beerisgood/Windows11_Privacy#2]
I don’t know whether this is appropriate for this repo but there is this official documentation about Microsoft Edge.
[https://learn.microsoft.com/en-us/microsoft-edge/privacy-whitepaper/](https://learn.microsoft.com/en-us/microsoft-edge/privacy-whitepaper/)

**Comment by beerisgood** [comment]
Thanks.
Added 🍺
